### PR TITLE
feat(population): Add country population stats.

### PR DESCRIPTION
**Pull request by GordonSmith**
Signed-off-by: Gordon Smith <gordonjsmith@gmail.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
Not sure if its of interest - but am using it to drive:  https://observablehq.com/@gordonsmith/covid-19-normalized-by-population

**Comment by fullergalway** [comment]
Thanks Gordon; yes it's probably relevant. Have you an attribution to include?
Also I noticed the ISO code for channel islands changed...? What's the basis for that and how is it a special case vs. say Northern Ireland? Thanks again. Rob.

**Comment by GordonSmith** [comment]
Rolled back the ISO code change (need to handle dup ISO2 codes better I guess).  Add comment re the data source:   //  Data from https://data.un.org/  ---

**Comment by fullergalway** [comment]
Cool I will try to get to that today or early tomorrow.

I might also the add in country_population field when
groupByCountryRegion() method is called for those of us using the
javascript methods.

Thanks again,
Rob

**Comment by GordonSmith** [comment]
That would be nice - I am manually joining here:   https://observablehq.com/@gordonsmith/covid-19-normalized-by-population but could switch to just use your dataset at that point...
(and need to auto update the current date still...)

**Comment by GordonSmith** [comment]
FYI - I mashed up Markdown and the Observable Runtime into a standalone web widget:  https://raw.githack.com/gordonsmith/Visualization/TMP/demos/storyboard/index.html

**Comment by fullergalway** [comment]
Let me get this right: you wrote a javascript library to let people write observablehq style pages in markdown and render on their own site?

**Comment by GordonSmith** [comment]
Yup - that is about the size of it...

**Comment by fullergalway** [comment]
Wow that's remarkable really. Very kewl.

**Pull request merged**
